'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Eris.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                 === DISCLAIMER ===
        '''
        '''This program is use for education purposes only, and it should not 
        '''be use beyond what is supposed to, without a mutual permission. 
        '''The author is not responsible or not held liable to any damage or 
        '''misuse that was made by using this program.
        '''
        '''USE AT YOUR OWN RISK..
        '''</summary>
        Friend ReadOnly Property Disclaimer() As String
            Get
                Return ResourceManager.GetString("Disclaimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eris Binary Padding program enlarge the size of a target file through
        '''a binary padding technique, where the target file&apos;s size was padded with
        '''a garbage bytes.
        '''
        '''USAGE:
        '''   dotnet eris.dll -path &lt;path&gt; [options]
        '''
        '''Argument:
        '''   -path &lt;path&gt;: A path of a file to be enlarge/padded.
        '''
        '''Options:
        '''   -sizeGB &lt;size&gt;: Adjust the size of a padded file in gigabytes (GB)
        '''   -sizeMB &lt;size&gt;: Adjust the size of a padded file in megabytes (MB)
        '''
        '''(If the option -sizeMB or -sizeGB was not specified, A default padded  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        ''' ________________
        ''' |&lt;&lt;&lt;&gt;&gt;&gt;|      | \
        ''' |&lt;&lt;&lt;&gt;&gt;&gt;|      |__\  EEEEEE  RRRRRR   IIIIII   SSSSS
        ''' |&lt;&lt;&lt;&gt;&gt;&gt;|         |  E       R     R    II    S
        ''' |&lt;&lt;&lt;&gt;&gt;&gt;|         |  EEEEEE  RRRRRR     II     SSSS
        ''' |&lt;&lt;&lt;&gt;&gt;&gt;|         |  E       R   R      II         S
        ''' |______|_________|  EEEEEE  R     R  IIIIII  SSSSS
        '''===========================================================
        '''	Author: PheeLeep
        '''	Repository: https://github.com/PheeLeep/Eris
        '''===========================================================.
        '''</summary>
        Friend ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
